export const colors = {
  background: "hsl(var(--background))",
  foreground: "hsl(var(--foreground))",
  primary: "hsl(var(--primary))",
  primaryForeground: "hsl(var(--primary-foreground))",
  secondary: "hsl(var(--secondary))",
  secondaryForeground: "hsl(var(--secondary-foreground))",
  muted: "hsl(var(--muted))",
  mutedForeground: "hsl(var(--muted-foreground))",
  accent: "hsl(var(--accent))",
  accentForeground: "hsl(var(--accent-foreground))",
  destructive: "hsl(var(--destructive))",
  destructiveForeground: "hsl(var(--destructive-foreground))",
  border: "hsl(var(--border))",
  input: "hsl(var(--input))",
  ring: "hsl(var(--ring))",
  success: "hsl(var(--success))",
  successForeground: "hsl(var(--success-foreground))",
  error: "hsl(var(--error))",
  errorForeground: "hsl(var(--error-foreground))",
  overlay: "hsla(var(--overlay), 0.7)",
  cropBox: "white",
  cropBoxDash: "dashed",
  resizeHandle: "white",
  activeItem: "white"
};
